### ISSUE TITLE
workload-identity compatibility

### ISSUE THREAD

**Issue by DerEinePete** [terraform-google-modules/terraform-google-kubernetes-engine#1582]
Hi,

In the workload-identity module is stated "Note: This module currently supports Kubernetes <= 1.23." Is this still the case?

https://cloud.google.com/kubernetes-engine/docs/release-schedule

The release schedule of the Google Cloud states, that it is already upgrading kubernetes to 1.24.
But I haven't experienced any issue.

**Comment by nicolaihald** [comment]
@DerEinePete : 
Just found this ticket and thought i'd post a comment. I'm not a maintainer, but it's likely related to https://github.com/hashicorp/terraform-provider-kubernetes/issues/1724  

`v1.24.0` includes a [breaking change](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#no-really-you-must-read-this-before-you-upgrade) as the default secret that is/was generated when creating a service account no longer will be generated. So, depending on how you manage your kubernetes service accounts, you may run into a warning similar to the one below. The fix is simple though. If i have time I may create a PR to fix it. That being said, we don't use this module so it's way down on the priority list. 


> _Warning: "default_secret_name" is no longer applicable for Kubernetes v1.24.0 and above_



 [v1.24 Release Notes - Breaking Change](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#no-really-you-must-read-this-before-you-upgrade):
> _"The `LegacyServiceAccountTokenNoAutoGeneration`eature gate is beta, and enabled by default. When enabled, Secret API objects containing service account tokens are no longer auto-generated for every ServiceAccount. Use the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API to acquire service account tokens, or if a non-expiring token is required, create a Secret API object for the token controller to populate with a service account token by following this [guide](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets). (https://github.com/kubernetes/kubernetes/pull/108309, [@zshihang](https://github.com/zshihang))"_


You can see an example of how to fix it here: 
- [Was fixed in https://github.com/oracle-quickstart/oci-micronaut/pull/31](https://github.com/oracle-quickstart/oci-micronaut/pull/31/files)

**Comment by henrybell** [comment]
Now that [Kubernetes version 1.24 or higher is the default across all GKE release channels](https://cloud.google.com/kubernetes-engine/docs/release-notes#current_versions), it would be most helpful to support 1.24+ in the [Workload Identity module](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/v25.0.0/modules/workload-identity). In the [Spanner Autoscaler we are currently pinning to 1.23](https://github.com/cloudspannerecosystem/autoscaler/blob/master/terraform/modules/autoscaler-cluster/variables.tf#L31), which [is scheduled to go EOL on 2023-07-31](https://cloud.google.com/kubernetes-engine/docs/release-schedule#schedule-for-release-channels).

**Comment by liggitt** [comment]
it looks like the bug in https://github.com/hashicorp/terraform-provider-kubernetes was fixed in https://github.com/hashicorp/terraform-provider-kubernetes/releases/tag/v2.13.0

I opened https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1595 to drop the 1.23 restriction and bump the required hashicorp/kubernetes version to one that includes the fix (2.13+), but it looks like that is blocked on an unrelated CI failure at HEAD

**Comment by apeabody** [comment]
Hi Everyone - Just a quick summary that the current version (`v25.0.0`) of `terraform-google-kubernetes-engine` can be used with Workload Identity and Kubernetes 1.24+, as long as your installed version of the `Kubernetes` provider is at least [`v2.13.0`](https://github.com/hashicorp/terraform-provider-kubernetes/releases/tag/v2.13.0).  The provider versions can be upgraded to the most recent permitted versions with `terraform init -upgrade`, and the installed provider versions verified with `terraform providers`.
