### ISSUE TITLE
Add support for google provider v5

### ISSUE THREAD

**Issue by dzoeteman** [terraform-google-modules/terraform-google-kubernetes-engine#1759]
### TL;DR

It would be great if the module could support the new v5 version of the google provider.
Specifically, this version of the provider has added the `deletion_protection` argument for clusters, which makes it so we can prevent the clusters created by the module from being destroyed.

### Additional information

v5 release changelog: https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.0.0

**Comment by ChrisNoSim** [comment]
Hi there,

We are encountering significant challenges due to the hashicorp/google provider version restriction in this module. It currently requires version 4.x, while other modules we use have already migrated to depend on version 5.x. At the moment we are unable to make changes to other clusters due to this dependency.

We're looking forward to support for Google Provider 5.x in this module. Any updates or timelines on this would be greatly appreciated.

Thank you for your attention to this issue, great job!

**Comment by TheKangaroo** [comment]
I believe this was fixed in #1761 and released in 29.0.0 a few hours ago.

**Comment by dzoeteman** [comment]
Closed based on #1761 , thanks!
