### ISSUE TITLE
Tests are failing on master

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-kubernetes-engine#233]
The integration tests are failing on master.

**Comment by ingwarr** [comment]
As a result of the research, I came to the conclusion that the tests fail because the wrong version of the provider is specified in examples, so we should remove versions from examples and add requirements to autogen/versions.tf. After running `make generate` all tests passed except stub-domains-private-local, but it removed from CI, I have ideas about how to make it work, I think it is an additional issue)
It looks like:

    terraform {
      required_version = ">= 0.12"
      required_providers {
        google-beta = "~> 2.12.0"
        google      = "~> 2.9.0"
      }
    }

I saw all the necessary changes made by @paulpalamarchuk in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/238

 Also for the new beta-cluster-local test, we need to add the appropriate role to GKE default service account  Cloud KMS CryptoKey Encrypter/Decrypter I think we should add it to README.md

**Comment by ingwarr** [comment]
![image](https://user-images.githubusercontent.com/2316547/63438132-81690e00-c434-11e9-920b-3d38f9b5e4ff.png)

**Comment by nick4fake** [comment]
@morgante regarding beta tests please check my comment [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/223)

**Comment by nick4fake** [comment]
@morgante could you please also confirm that stub-domains-private-local is also in the scope? It has been removed from CI, so we are not sure.

**Comment by morgante** [comment]
@nick4fake I think you might have linked to the wrong comment?

We can skip stub-domains-private-local if it's causing issues.

**Comment by morgante** [comment]
We should NOT remove versions from examples, but simply update them to the correct version.
