### ISSUE TITLE
enable_shielded_nodes variable does not enable Secure Boot in beta-private-cluster module

### ISSUE THREAD

**Issue by james-mcgoodwin** [terraform-google-modules/terraform-google-kubernetes-engine#501]
We are using the beta-private-cluster to instantiate our GKE clusters, and are trying to satisfy the CIS GKE Control 6.5.7 ("Ensure Secure Boot for Shielded GKE Nodes is Enabled")

When we set enable_shielded_nodes = true, this activates the Shielded Node feature in the cluster, but our expectation was that this would also enable Secure Boot. 

This seemed to be part of the discussion in https://github.com/terraform-providers/terraform-provider-google/issues/4434 and in the absence of a discrete setting titled 'enable_secure_boot = true', our hope was that activating Shielded Nodes would be enough. 

Is Secure Boot supported in the beta-private-cluster module?

**Comment by morgante** [comment]
Please file a bug on the provider, as there's nothing we can do on the module if there's not an option for managing secure boot on the provider.

**Comment by Dev25** [comment]
There is a `shielded_instance_config` via the provider that we can set via dynamic block.

By default secure boot isn't enabled when you enable shielded nodes because it can block certain workloads so we probably want to expose `enable_secure_boot` in this module to enable that.

https://www.terraform.io/docs/providers/google/r/container_cluster.html#shielded_instance_config

>The shielded_instance_config block supports:

>enable_secure_boot (Optional) - Defines if the instance has Secure Boot enabled.
Secure Boot helps ensure that the system only runs authentic software by verifying the digital signature of all boot components, and halting the boot process if signature verification fails. Defaults to false.

>enable_integrity_monitoring (Optional) - Defines if the instance has integrity monitoring enabled.
Enables monitoring and attestation of the boot integrity of the instance. The attestation is performed against the integrity policy baseline. This baseline is initially derived from the implicitly trusted boot image when the instance is created. Defaults to true.

**Comment by morgante** [comment]
@Dev25 Thanks for the missing connection, I should've checked the docs. This does seem like a good addition.

I suggest we add an `enable_secure_boot` variable.

**Comment by jmymy** [comment]
The var already exists.

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/beta-private-cluster/cluster.tf#L385
```
    shielded_instance_config {
      enable_secure_boot          = lookup(each.value, "enable_secure_boot", false)
      enable_integrity_monitoring = lookup(each.value, "enable_integrity_monitoring", true)
    }
  }
```

Confirmed working with this config:

```
module "cluster" {
  source                       = "terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster-update-variant"
  version                      = "9.0.0"
  authenticator_security_group = "gke-security-groups@XXX"
  description                  = "Managed by Terraform"
....
  network_policy         = false
  zones                  = ["us-central1-a", "us-central1-b", "us-central1-f"]
  node_metadata          = "GKE_METADATA_SERVER"
  node_pools = [
    {
      name         = "pool-01"
      machine_type = "n1-standard-2"
      auto_repair  = true
      auto_upgrade = true
      enable_secure_boot = true
      enable_integrity_monitoring = true
    },
  ]
}
```

**Comment by c0ffeec0der** [comment]
Documentation updated in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/525
