### ISSUE TITLE
accelerator_type=nvidia-tesla-t4 and remove_default_node_pool=true: GPU k8s taints sometimes missing

### ISSUE THREAD

**Issue by thomas-riccardi** [terraform-google-modules/terraform-google-kubernetes-engine#703]
I created a cluster with: (module 8.1.0 and google provider 3.16.0)
```hcl
module "gke" {
  source  = "terraform-google-modules/kubernetes-engine/google//modules/beta-public-cluster"
  version = "~> 8.1"
...
  remove_default_node_pool = true
  node_pools = [
    {
      name = "default"
...
    },
    {
      name = "gpu-t4"
...
      accelerator_count = 1
      accelerator_type  = "nvidia-tesla-t4"
...
    }
}
```

Result: my `gpu-t4` nodepool has no gpu k8s taint (leading to filling these nodes with pods not needed a gpu, saturating the nodes, blocking pods really needing gpus..)

https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#create says:
> Note: If a GPU node pool is added to a cluster where all the existing node pools are GPU node pools, or if you are creating a new cluster with a GPU attached default pool, the above taint will not be added to the GPU nodes. The taint will also not be added to the existing GPU nodes retrospectively when a non-GPU node pool is added afterwards.

I believe the `remove_default_node_pool = true` creates a race-condition where the default nodepool is deleted, then the gpu nodepool is created all alone, resulting in the documented case when GKE doesn't add the taints (then the default nodepool is created).

Maybe a workaround would be to add a dependency between the node pools themselves so the gpu ones depend on a non-gpu one to avoid that case? It doesn't seem doable for now though.

**Comment by thomas-riccardi** [comment]
It may explain #173

**Comment by bharathkkb** [comment]
@thomas-riccardi I may need to test this out to see how the interactions with the auto taint works. As a workaround would manually specifying it via `node_pools_taints` be sufficient for your usecase?

**Comment by thomas-riccardi** [comment]
@bharathkkb indeed `node_pools_taints` could help for new clusters as a workaround, assuming GKE temporarily accepts clusters with only one node-pool with the gpu taint (blocking all standard (and system) pods), while waiting for the second, standard, node-pool to be created.
For existing clusters taints are not editable IIRC, so it would delete and recreate a new node-pool; to minimize downtime I went another way: temporarily duplicate the node-pool with a new name, then delete the old node-pool.
Thanks for the quick workaround suggestion!

**Comment by vasrem** [comment]
I face a different issue here which might be related to this one. I basically have a cluster which contains only non GPU nodes. When I add a new node pool with GPU nodes in the already running cluster by also providing a taint like this:
```
{
  effect = "NO_SCHEDULE"
  key    = "nvidia.com/gpu"
  value  = "present"
}

```
Terraform complains with the following error:
```
Error: error creating NodePool: googleapi: Error 400: Found more than one taint with key nvidia.com/gpu and effect NO_SCHEDULE., badRequest
```
If I remove the taint completely from Terraform to leverage the automatic tainting provided by GKE, `terraform apply` goes through. However, in the next plan, I see that Terraform wants to remove the taint mentioned above because it's not stated in the GKE module call.

In my opinion, what would make sense in Terraform (UX wise) is one of the following:
1. Don't mutate taints on the fly and instead let the user add this taint for GPU nodes. (drawback: we need to always add the taint for GPU nodes which might be error prone)
1. Add the GPU taint automatically but stop Terraform from removing it in the next plan.
1. Make user-input in the GKE module override the default taint that may be added(i.e. the one mentioned above) by GKE itself in order to not get to the error mentioned above. (drawback: user has the flexibility to override the default one provided by GKE which can be error prone).

If you ask me, I like option 2 > 1 > 3.

I'm using the `beta-private-cluster-update-variant` of version `11.1.0`.

**Comment by morgante** [comment]
Hi @vasrem, could you share your full Terraform config + Terraform plan? i suspect something in the provider or GKE API has changed to cause this error.

**Comment by andre-lx** [comment]
Hi @morgante.

I can share my experience. 

Right now, we have a lot of pools, and with our gpu pools we have our own taints, but we need to comment this taint in the first deploy:

```
{
  effect = "NO_SCHEDULE"
  key    = "nvidia.com/gpu"
  value  = "present"
}
```

Otherwise, terraform will output the error described by @vasrem :
```
Error: error creating NodePool: googleapi: Error 400: Found more than one taint with key nvidia.com/gpu and effect NO_SCHEDULE., badRequest
```

After the first deploy, we need to uncomment in the subsequent deploys (`terraform apply`), or terraform will replace the node_pool each time we run the apply command. 

Thanks

**Comment by andre-lx** [comment]
Hi. This is an issue with the google provider, and not with the module. You can find more info in my open issue:

https://github.com/hashicorp/terraform-provider-google/issues/7928
