### ISSUE TITLE
using kubectl in terraform with bastion host

### ISSUE THREAD

**Issue by mateuszm123111** [terraform-google-modules/terraform-google-kubernetes-engine#769]
Hi all,

I'm wondering if is it possible to use kubectl in terraform with private cluster and bastion host?

I was trying to apply first bastion host and gke with terraform, then login on another terminal window to bastion host, set proxy as environment variable(in this case I'm able to do just "kubectl" from local machine, so it means terraform also can), and then run terraform, but proxy to kubectl doesn't work with terraform, because I get:
`Error loading state: Failed to open state file at gs://mytfstate/state/tfstate: Get "https://storage.googleapis.com/mytfstate/state/tfstate": Post "https://oauth2.googleapis.com/token": proxyconnect tcp: dial tcp [::1]:8888: connect: connection refused`

Is it possible to use them both? If yes, could someone help me to achieve this?  Or better approach would be to run terraform from bastion host, or other VM which can directly access cluster?

Thanks in advance

**Comment by bharathkkb** [comment]
Hi @mateuszm123111 
Looks like Terraform is also trying to tunnel via that proxy possibly due to `HTTPS_PROXY` being set.  You may have to configure `NO_PROXY` or you can use this [alternative method](https://cloud.google.com/solutions/creating-kubernetes-engine-private-clusters-with-net-proxies) for automation.

**Comment by bharathkkb** [comment]
@mateuszm123111 feel free to reopen if needed
