### ISSUE TITLE
Making `identity_namespace` configurable in safer-cluster* submodules

### ISSUE THREAD

**Issue by xingao267** [terraform-google-modules/terraform-google-kubernetes-engine#784]
Workload Identity is currently always enabled in the `safer-cluster` and `safer-cluster-update-variant`. This behavior is controlled by the field  `identity_namespace`.  We want to leverage features in the safer-cluster but disable workload identity. Is it possible to expose this input in the safer-cluster* submodules so I can configure it?

If this proposal sounds good to you, I can work on a PR to support it.

**Comment by morgante** [comment]
I'm not sure we should expose this.

The goal of the safer cluster submodules is provide a strongly opinionated view on what a secure cluster looks like.

Using workload identity is our best practice recommendation. Can you clarify more about why you want to disable it?

**Comment by xingao267** [comment]
IIUC, Workload Identity is preferred when multiple applications are run in the same cluster, and to prevent downloading json keys to use in different pods, it's more secure to use Workload Identity so different k8s SA can be assigned to different pods and linked to different GCP SAs which has app-specific permissions, so each pod's permissions are configured at a finer granularity.

However, in most cases, our customers run just one application in the cluster with one IAM Service Account identity. It's simple and intuitive to just grant that GCP SA necessary permission to do the work (access db, buckets etc). Same as using Workload Identity, there is no additional SA json key handling in this case.

In these kind of simple but quite common cases (I think for a lot of other customers who just get started with GKE as well), we would like to leverage other security features configured by the `safer-cluster-update-variant` module, but having to use Workload Identity adds unnecessary complexity to the workflow. I tried supplying a Service Account when calling the `safer-cluster-update-variant` module via the [compute_engine_service_account](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/safer-cluster-update-variant/variables.tf#L307) field, but the application doesn't seem to use that SA when accessing other Cloud resources. `safer-cluster-update-variant` itself doesn't seem to work out-of-the-box in terms of creating the k8s SA and setting up the bindings between that and GCP SA. I think I need to use the `workload_identity` submodule for that on top of the `safer-cluster-update-variant` module which sets up the cluster.

So I think setting Workload Identity to be enabled by default but enabling users to configure `identity_namespace` and `node_metadata` can make this module fit more use cases.

**Comment by morgante** [comment]
Even if you're only running a single application in your cluster, WI would still be recommended as it's simply more secure. Using node IAM is saying that *any workload* which manages to get onto your cluster (including unexpectedly) should inherit the same permissions. It's inherently less secure and similar to using the Compute Engine default service account: an easy default, but also a common source of accidental compromises.

Yes, this is not going to be as simple. That's why we don't mandate it for _all_ clusters. But for the most secure clusters, we recommend using Workload Identity even if it's a single-tenant cluster.

If customers absolutely don't want to do that, they can still directly compose the base modules.

(That being said, I'd absolutely be open to enhancements which make working with Workload Identity easier. Maybe we could even provide a "default" WI binding.)

**Comment by xingao267** [comment]
Thanks for the explanation. I'll experiment something with a default KSA binding. Closing for now.
