### ISSUE TITLE
Question: what is the logic behind setting min_master_version

### ISSUE THREAD

**Issue by andrewnazarov** [terraform-google-modules/terraform-google-kubernetes-engine#803]
I would like to understand the logic behind
```
min_master_version = var.release_channel != null ? null : local.master_version
```

We want to set and manage versions by ourselves. Here if we set the release channel to "UNSPECIFIED" we don't have a possibility to set a version anymore, because it will be set to `null`. We can set and manage versions only when `release_channel` is null. Is this expected?

**Comment by morgante** [comment]
Setting release channel to `UNSPECIFIED` should be equivalent to setting it to `null`. (We could also update this logic to check for `UNSPECIFIED` specifically.)

**Comment by thpang** [comment]
Being able to set both variables is quite valuable. Being able to code the exact version of kubernetes I am installing. I know it could be updated automatically in the future, but at least at the deployment of the infrastructure would be exactly what I coded or it would throw and error.

For example I've look at the `gcloud` command for my zone and would like to use the `RAPID` channel. The output would be:
```
 $ gcloud container get-server-config --format "yaml(channels)" --zone us-east1-b
Fetching server config for us-east1-b
channels:
- channel: RAPID
  defaultVersion: 1.19.8-gke.1000
  validVersions:
  - 1.20.4-gke.1800
  - 1.19.8-gke.1600
  - 1.19.8-gke.1000
- channel: REGULAR
  defaultVersion: 1.18.15-gke.1501
  validVersions:
  - 1.18.16-gke.302
  - 1.18.15-gke.1502
  - 1.18.15-gke.1501
- channel: STABLE
  defaultVersion: 1.17.17-gke.1101
  validVersions:
  - 1.17.17-gke.2800
  - 1.17.17-gke.1101
  - 1.16.15-gke.7801
```
So from this list I would then set the following values when using this module:
```
release_channel    = "RAPID"
kubernetes_version = "1.20.4-gke.1800"
```
Which if is passed into the `googe_cloud_container` resource instead of using this module would work just fine and assign what was asked.

However, in this example, my actual `kubernetes_version` would be set to the channel's current default which is: `1.19.8-gke.1000` 

I found that code was updated here: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/commit/2cb4fae57cb580daba6dc64c7564dcaa7df4efd6 with no indication or comment on why it was adjusted.

Looking to see if this can be altered, changed back, or adjusted so the user can decide on the value as the change seems counter to what one would want when using a declarative tool like terraform to set up a kubernetes cluster.

**Comment by morgante** [comment]
We take the point of view that mixing release channels and explicitly specifying a Kubernetes version is *not* declarative. It's true that the API will technically allow you to do this, but when you opt in to a release channel you're implicitly asking Google to take over the choice of cluster version for you and Google will automatically issue updates. This means that your declarative config might no longer be valid if you specified a lower version.

With this module, you should either choose to use a release channel (in which case, Google will upgrade you automatically) or to manage versions yourself. If you want to manage versions yourself, that's perfectly valid but then you don't need release channels.

**Comment by thpang** [comment]
I understand, but don't actually agree with the statement that creating a cluster by mixing a release channel and version is not declarative from your point of view. If you take that point of view, where do you state this in your documentation? Terraform by its nature is `declarative` and this module takes that stance one can simply `imply` which version you'd like to use and Google will do the rest. What if I have to alter the cluster in a way that would require one to use `terraform apply . . .` these alterations and the `implied` change(s) Google made to the version applied differs from the current terraform state. Will the cluster be destroyed/altered/etc. No information on this is provided.

This change was recent and not much was used to describe why that change was implemented, allowed into the code, and is only now enforced in the feature link included above. Other providers allow this type of kubernetes versioning in a very `declarative` way.  and it's actually allowed here: 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster

If you can provide more robust and clear documentation on this limitation with this module and an examples of how to use this module using both a channel and exact version as stated above that would be most helpful. 

Having this type of anti-pattern when one uses this module to stand up a kubernetes cluster using terraform is very counter to its declarative nature.
