### ISSUE TITLE
terraform-google-kubernetes-engine 16.0 forces replacement of existing workload-identities

### ISSUE THREAD

**Issue by vfiset** [terraform-google-modules/terraform-google-kubernetes-engine#959]
While upgrading terraform-google-kubernetes-engine from 15.0.2 to 16.0, all the workload-indentities that are already existing are flagged as to be replaced by a terraform plan.

**Comment by bharathkkb** [comment]
Thanks for the report @vfiset 

I think this may have been due to the resource rename in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/955/files from `resource "google_service_account" "cluster_service_account"` to `resource "google_service_account" "main"`. I'll test a repro, if you have logs that would be useful.

**Comment by bharathkkb** [comment]
@vfiset I was able to repro and reverting the resource name back prevents replacement. PR #960 with fix.
